### ISSUE TITLE
Samples Script

### ISSUE THREAD

**Issue by cyberience** [CryptoverseRocks/token-test-suite#6]
expect(log.args.value).to.be.bignumber.equal(amount);
Causing the following error.
 TypeError: Cannot read property 'isBigNumber' of undefined
      at isBigNumber (node_modules/chai-bignumber/chai-bignumber.js:11:21)
      at convert (node_modules/chai-bignumber/chai-bignumber.js:21:18)
      at Proxy.<anonymous> (node_modules/chai-bignumber/chai-bignumber.js:43:26)
      at Proxy.overwritingMethodWrapper (node_modules/chai/lib/chai/utils/overwriteMethod.js:78:33)
      at testTransferEvent (node_modules/token-test-suite/lib/suite.js:513:44)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:182:7)

If I comment out this line in a couple of places, the tests are good, and the cases are tested. only this line presents a load of errors.

**Comment by matejkonrad** [comment]
Hey there, there is an easy fix to this, just run `npm install --save chai-bignumber`

**Comment by mancze** [comment]
Yeah, there was an issue with declared dependencies. This is fixed in v0.1.1 of https://github.com/mancze/token-test-suite/ .
